export const images = [
  { id: 1, src: './avengers/ant-man.jpg', name:'Ant Man'},
  { id: 2, src: './avengers/black-panter.jpg', name:'Black Panter'},
  { id: 3, src: './avengers/black-widow.jpg', name:'Black Widow'},
  { id: 4, src: './avengers/captain-america.jpg', name:'Captain America'},
  { id: 5, src: './avengers/captain-marvel.jpg', name:'Captain Marvel'},
  { id: 6, src: './avengers/dr-strange.jpg', name:'Dr. Strange'},
  { id: 7, src: './avengers/drax.jpg', name:'Drax'},
  { id: 8, src: './avengers/falcon.jpg', name:'Falcon'},
  { id: 9, src: './avengers/gamora.jpg', name:'Gamora'},
  { id: 10, src: './avengers/groot.jpg', name:'Groot'},
  { id: 11, src: './avengers/hawkeye.jpg', name:'Hawkeye'},
  { id: 12, src: './avengers/hulk.jpg', name:'Hulk'},
  { id: 13, src: './avengers/iron-man.jpg', name:'Iron Man'},
  { id: 14, src: './avengers/loki.jpg', name:'Loki'},
  { id: 15, src: './avengers/nebula.jpg', name:'Nebula'},
  { id: 16, src: './avengers/rocket.jpg', name:'Rocket'},
  { id: 17, src: './avengers/scarlet-witch.jpg', name:'Scarlet Witch'},
  { id: 18, src: './avengers/spiderman.jpg', name:'Spiderman'},
  { id: 19, src: './avengers/star-lord.jpg', name:'Star Lord'},
  { id: 20, src: './avengers/thor.jpg', name:'Thor'},
  { id: 21, src: './avengers/war-machine.jpg', name:'War Machine'},
  { id: 22, src: './avengers/winter-soldier.jpg', name:'Winter Soldier'}
];